In [1]:
import pickle
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The savefig.frameon rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The verbose.level rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.
In C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: 
The verbose.fileo rcparam was deprecated in Matplotlib 3.1 and will be removed in 3.3.


In [2]:
loadModel_log = pickle.load(open('pipe_logreg_bank.sav', 'rb'))

In [3]:
loadModel_xgb = pickle.load(open('xgb_bank.sav', 'rb'))

In [4]:
bank_model = pd.read_csv('bankdum_final_logreg.csv')

In [5]:
bank_model.head()

Age  Euribor 3M  Consumer Price Index  Consumer Confidence Index  \
0   56       4.857                93.994                      -36.4   
1   57       4.857                93.994                      -36.4   
2   37       4.857                93.994                      -36.4   
3   40       4.857                93.994                      -36.4   
4   56       4.857                93.994                      -36.4   

   Job_Admin.  Job_Blue-collar  Job_Entrepreneur  Job_Housemaid  \
0           0                0                 0              1   
1           0                0                 0              0   
2           0                0                 0              0   
3           1                0                 0              0   
4           0                0                 0              0   

   Job_Management  Job_Retired  ...  Marital Status_Single  \
0               0            0  ...                      0   
1               0            0  ...                      0   
2               0            0  ...                      0   
3               0            0  ...                      0   
4               0            0  ...                      0   

   Marital Status_Unknown  Education_Basic 4y  Education_Basic 6y  \
0                       0                   1                   0   
1                       0                   0                   0   
2                       0                   0                   0   
3                       0                   0                   1   
4                       0                   0                   0   

   Education_Basic 9y  Education_High school  Education_Illiterate  \
0                   0                      0                     0   
1                   0                      1                     0   
2                   0                      1                     0   
3                   0                      0                     0   
4                   0                      1                     0   

   Education_Professional course  Education_University degree  \
0                              0                            0   
1                              0                            0   
2                              0                            0   
3                              0                            0   
4                              0                            0   

   Education_Unknown  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  

[5 rows x 28 columns]

In [6]:
pd.set_option('display.max_columns', None)

In [7]:
bank_model.head()

Age  Euribor 3M  Consumer Price Index  Consumer Confidence Index  \
0   56       4.857                93.994                      -36.4   
1   57       4.857                93.994                      -36.4   
2   37       4.857                93.994                      -36.4   
3   40       4.857                93.994                      -36.4   
4   56       4.857                93.994                      -36.4   

   Job_Admin.  Job_Blue-collar  Job_Entrepreneur  Job_Housemaid  \
0           0                0                 0              1   
1           0                0                 0              0   
2           0                0                 0              0   
3           1                0                 0              0   
4           0                0                 0              0   

   Job_Management  Job_Retired  Job_Self-employed  Job_Services  Job_Student  \
0               0            0                  0             0            0   
1               0            0                  0             1            0   
2               0            0                  0             1            0   
3               0            0                  0             0            0   
4               0            0                  0             1            0   

   Job_Technician  Job_Unemployed  Job_Unknown  Marital Status_Divorced  \
0               0               0            0                        0   
1               0               0            0                        0   
2               0               0            0                        0   
3               0               0            0                        0   
4               0               0            0                        0   

   Marital Status_Married  Marital Status_Single  Marital Status_Unknown  \
0                       1                      0                       0   
1                       1                      0                       0   
2                       1                      0                       0   
3                       1                      0                       0   
4                       1                      0                       0   

   Education_Basic 4y  Education_Basic 6y  Education_Basic 9y  \
0                   1                   0                   0   
1                   0                   0                   0   
2                   0                   0                   0   
3                   0                   1                   0   
4                   0                   0                   0   

   Education_High school  Education_Illiterate  Education_Professional course  \
0                      0                     0                              0   
1                      1                     0                              0   
2                      1                     0                              0   
3                      0                     0                              0   
4                      1                     0                              0   

   Education_University degree  Education_Unknown  
0                            0                  0  
1                            0                  0  
2                            0                  0  
3                            0                  0  
4                            0                  0

In [41]:
data1 = [(56, 4.857, 93.994,-36.4, 0, 0, 0, 1, 0, 0, 0,0,0,0,0,0, 0, 1, 0, 0, 1, 0,0,0,0,0,0,0)]

In [9]:
bank_model.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 28 columns):
Age                              41188 non-null int64
Euribor 3M                       41188 non-null float64
Consumer Price Index             41188 non-null float64
Consumer Confidence Index        41188 non-null float64
Job_Admin.                       41188 non-null int64
Job_Blue-collar                  41188 non-null int64
Job_Entrepreneur                 41188 non-null int64
Job_Housemaid                    41188 non-null int64
Job_Management                   41188 non-null int64
Job_Retired                      41188 non-null int64
Job_Self-employed                41188 non-null int64
Job_Services                     41188 non-null int64
Job_Student                      41188 non-null int64
Job_Technician                   41188 non-null int64
Job_Unemployed                   41188 non-null int64
Job_Unknown                      41188 non-null int64
Marital Status_Divorc

In [17]:
dat1 = pd.DataFrame(data1).T

In [19]:
dat1

0      1       2     3    4    5    6    7    8    9   10   11   12  \
0  56.0  4.857  93.994 -36.4  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0   

    13   14   15   16   17   18   19   20   21   22   23   24   25   26   27  
0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [42]:
dat1log = pd.DataFrame(data1)

In [43]:
t_log2 = loadModel_log.predict(dat1log)

In [44]:
t_log2

array([0], dtype=int64)

In [20]:
t_log1 = loadModel_log.predict(dat1)

In [21]:
t_log1

array([0], dtype=int64)

In [27]:
loadModel_log.predict_proba(dat1)[]

array([[0.7097331, 0.2902669]])

In [24]:
loadModel_log[1]

LogisticRegression(C=1, class_weight='balanced', dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1500,
                   multi_class='auto', n_jobs=None, penalty='l1',
                   random_state=None, solver='saga', tol=0.0001, verbose=0,
                   warm_start=False)

In [29]:
loadModel_log.predict_proba(dat1)[0][1]

0.2902668962430438

In [30]:
t_xgb1 = loadModel_xgb.predict(dat1)

ValueError: feature_names mismatch: ['Age', 'Euribor 3M', 'Consumer Price Index', 'Consumer Confidence Index', 'Job_Admin.', 'Job_Blue-collar', 'Job_Entrepreneur', 'Job_Housemaid', 'Job_Management', 'Job_Retired', 'Job_Self-employed', 'Job_Services', 'Job_Student', 'Job_Technician', 'Job_Unemployed', 'Job_Unknown', 'Marital Status_Divorced', 'Marital Status_Married', 'Marital Status_Single', 'Marital Status_Unknown', 'Education_Basic 4y', 'Education_Basic 6y', 'Education_Basic 9y', 'Education_High school', 'Education_Illiterate', 'Education_Professional course', 'Education_University degree', 'Education_Unknown'] ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27']
expected Consumer Price Index, Euribor 3M, Education_University degree, Job_Student, Job_Unemployed, Marital Status_Single, Job_Entrepreneur, Education_Basic 9y, Job_Retired, Education_Illiterate, Job_Self-employed, Marital Status_Unknown, Education_High school, Job_Services, Education_Unknown, Job_Housemaid, Education_Professional course, Job_Unknown, Job_Blue-collar, Education_Basic 4y, Job_Technician, Marital Status_Divorced, Job_Management, Consumer Confidence Index, Job_Admin., Marital Status_Married, Age, Education_Basic 6y in input data
training data did not have the following fields: 19, 13, 5, 23, 8, 15, 14, 16, 4, 7, 20, 1, 18, 27, 22, 6, 0, 21, 12, 17, 3, 25, 24, 11, 26, 2, 9, 10

In [34]:
dat1

0      1       2     3    4    5    6    7    8    9   10   11   12  \
0  56.0  4.857  93.994 -36.4  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0   

    13   14   15   16   17   18   19   20   21   22   23   24   25   26   27  
0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [35]:
dat1xgb = pd.DataFrame(dat1, columns = ['Age', 'Euribor 3M', 'Consumer Price Index', 'Consumer Confidence Index', 
                                         'Job_Admin.', 'Job_Blue-collar', 'Job_Entrepreneur', 'Job_Housemaid', 
                                         'Job_Management', 'Job_Retired', 'Job_Self-employed', 'Job_Services', 'Job_Student', 'Job_Technician', 
                                        'Job_Unemployed', 'Job_Unknown', 'Marital Status_Divorced', 'Marital Status_Married', 'Marital Status_Single', 
                                         'Marital Status_Unknown', 'Education_Basic 4y', 'Education_Basic 6y', 
                                         'Education_Basic 9y', 'Education_High school', 'Education_Illiterate', 
                                         'Education_Professional course', 'Education_University degree', 'Education_Unknown'])

In [36]:
t_xgb1 = loadModel_xgb.predict(dat1xgb)

In [37]:
t_xgb1

array([0], dtype=int64)

In [47]:
probaYes = loadModel_xgb.predict_proba(dat1xgb)[0][1]

In [56]:
result = 'The probability of accepting the bank offer is : {}'.format(probaYes)

In [57]:
result

'The probability of accepting the bank offer is : 0.0052211289294064045'

In [60]:
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

In [61]:
model = GaussianNB(RandomForestClassifier(SelectFromModel(input_matrix, criterion=entropy, max_features=0.5, n_estimators=100, threshold=0.05), bootstrap=True, criterion=gini, max_features=0.8, min_samples_leaf=16, min_samples_split=20, n_estimators=100))

NameError: name 'input_matrix' is not defined

### Based on previous notebook (Supervised Learning Part 4) I ran an autoML to look for a better model. Let's load it here

In [62]:
bank_dash = pd.read_csv('bank_dash.csv')

In [63]:
target = bank_dash['y'].apply(lambda x: 1 if x =='yes' else 0)

In [64]:
tpotdat = pd.concat([bank_model, target], axis =1)

In [65]:
tpotdat.head()

Age  Euribor 3M  Consumer Price Index  Consumer Confidence Index  \
0   56       4.857                93.994                      -36.4   
1   57       4.857                93.994                      -36.4   
2   37       4.857                93.994                      -36.4   
3   40       4.857                93.994                      -36.4   
4   56       4.857                93.994                      -36.4   

   Job_Admin.  Job_Blue-collar  Job_Entrepreneur  Job_Housemaid  \
0           0                0                 0              1   
1           0                0                 0              0   
2           0                0                 0              0   
3           1                0                 0              0   
4           0                0                 0              0   

   Job_Management  Job_Retired  Job_Self-employed  Job_Services  Job_Student  \
0               0            0                  0             0            0   
1               0            0                  0             1            0   
2               0            0                  0             1            0   
3               0            0                  0             0            0   
4               0            0                  0             1            0   

   Job_Technician  Job_Unemployed  Job_Unknown  Marital Status_Divorced  \
0               0               0            0                        0   
1               0               0            0                        0   
2               0               0            0                        0   
3               0               0            0                        0   
4               0               0            0                        0   

   Marital Status_Married  Marital Status_Single  Marital Status_Unknown  \
0                       1                      0                       0   
1                       1                      0                       0   
2                       1                      0                       0   
3                       1                      0                       0   
4                       1                      0                       0   

   Education_Basic 4y  Education_Basic 6y  Education_Basic 9y  \
0                   1                   0                   0   
1                   0                   0                   0   
2                   0                   0                   0   
3                   0                   1                   0   
4                   0                   0                   0   

   Education_High school  Education_Illiterate  Education_Professional course  \
0                      0                     0                              0   
1                      1                     0                              0   
2                      1                     0                              0   
3                      0                     0                              0   
4                      1                     0                              0   

   Education_University degree  Education_Unknown  y  
0                            0                  0  0  
1                            0                  0  0  
2                            0                  0  0  
3                            0                  0  0  
4                            0                  0  0

In [67]:
tpotdat.rename(columns = {'y': 'target'}, inplace = True)

In [68]:
tpotdat.head()

Age  Euribor 3M  Consumer Price Index  Consumer Confidence Index  \
0   56       4.857                93.994                      -36.4   
1   57       4.857                93.994                      -36.4   
2   37       4.857                93.994                      -36.4   
3   40       4.857                93.994                      -36.4   
4   56       4.857                93.994                      -36.4   

   Job_Admin.  Job_Blue-collar  Job_Entrepreneur  Job_Housemaid  \
0           0                0                 0              1   
1           0                0                 0              0   
2           0                0                 0              0   
3           1                0                 0              0   
4           0                0                 0              0   

   Job_Management  Job_Retired  Job_Self-employed  Job_Services  Job_Student  \
0               0            0                  0             0            0   
1               0            0                  0             1            0   
2               0            0                  0             1            0   
3               0            0                  0             0            0   
4               0            0                  0             1            0   

   Job_Technician  Job_Unemployed  Job_Unknown  Marital Status_Divorced  \
0               0               0            0                        0   
1               0               0            0                        0   
2               0               0            0                        0   
3               0               0            0                        0   
4               0               0            0                        0   

   Marital Status_Married  Marital Status_Single  Marital Status_Unknown  \
0                       1                      0                       0   
1                       1                      0                       0   
2                       1                      0                       0   
3                       1                      0                       0   
4                       1                      0                       0   

   Education_Basic 4y  Education_Basic 6y  Education_Basic 9y  \
0                   1                   0                   0   
1                   0                   0                   0   
2                   0                   0                   0   
3                   0                   1                   0   
4                   0                   0                   0   

   Education_High school  Education_Illiterate  Education_Professional course  \
0                      0                     0                              0   
1                      1                     0                              0   
2                      1                     0                              0   
3                      0                     0                              0   
4                      1                     0                              0   

   Education_University degree  Education_Unknown  target  
0                            0                  0       0  
1                            0                  0       0  
2                            0                  0       0  
3                            0                  0       0  
4                            0                  0       0

In [69]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.feature_selection import RFE
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.pipeline import make_pipeline, make_union
from tpot.builtins import StackingEstimator

# NOTE: Make sure that the outcome column is labeled 'target' in the data file
tpot_data = tpotdat
features = tpot_data.drop('target', axis=1)
training_features, testing_features, training_target, testing_target = \
            train_test_split(features, tpot_data['target'], random_state=None)

# Average CV score on the training set was: 0.4606549258592689
exported_pipeline = make_pipeline(
    RFE(estimator=ExtraTreesClassifier(criterion="gini", max_features=0.3, n_estimators=100), step=0.1),
    StackingEstimator(estimator=ExtraTreesClassifier(bootstrap=False, criterion="entropy", max_features=0.7500000000000001, min_samples_leaf=9, min_samples_split=20, n_estimators=100)),
    PCA(iterated_power=8, svd_solver="randomized"),
    GaussianNB()
)

exported_pipeline.fit(training_features, training_target)
results = exported_pipeline.predict(testing_features)


In [70]:
results

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [71]:
from sklearn.metrics import classification_report, confusion_matrix, f1_score

In [72]:
print(classification_report(testing_target, results))

              precision    recall  f1-score   support

           0       0.94      0.92      0.93      9180
           1       0.42      0.50      0.46      1117

    accuracy                           0.87     10297
   macro avg       0.68      0.71      0.69     10297
weighted avg       0.88      0.87      0.88     10297



In [73]:
print(confusion_matrix(testing_target, results))

[[8419  761]
 [ 560  557]]


In [74]:
coba = exported_pipeline.predict(bank_model)

### Now let's compare the models when predicting the whole dataset

In [75]:
## AUTOMl model
print(confusion_matrix(target, coba))

[[33632  2916]
 [ 2223  2417]]


In [76]:
coba_log = loadModel_log.predict(bank_model)

In [77]:
## logistic regression
print(confusion_matrix(target, coba_log))

[[26376 10172]
 [ 1371  3269]]


In [78]:
coba_xgb = loadModel_xgb.predict(bank_model)

In [79]:
## XGB model
print(confusion_matrix(target, coba_xgb))

[[35869   679]
 [ 2353  2287]]


> Based on the result above: 
* log-reg model is the one that helps bank to acquire the most positive customer, but at the cost of a big number of False Positives -- suitable for bank with aggresive strategy (high recall score)
* XGB model is the conservative one --  more careful in predicting the positive cases, but across all positive predictions, there are more True Positives than False Positive (high precision score)
* AutoML model is more balanced -- according to the scores generated (Difference in precision and recall scores are not really extreme)


> Conclusion:
* Now we reached the end of my project. Based on the result above, personally I think logistic regression can still be optimised -- mainly because of a big number in False Positives. On the other hand, XGB is performing really well, although bank might miss half of the total positive customers (seems like XGB preferred to predict No instead of Yes).
* However at this point, to choose one exact model, we need to know the bank strategy and also the cost of customer acquisition (the cost of calling and sales employee). Although logistic regression seems bad (again, according to the big number of False Positives), but it actually have decreased the number of total customer that needs to be called.
* There is still a lot to be explored in this bank dataset.


### testing for model deployment -- for dashboard application

In [80]:
import pickle
filename = 'pipe_tpot.sav';
pickle.dump(exported_pipeline, open(filename, 'wb'))

In [81]:
loadModel_tpot = pickle.load(open('pipe_tpot.sav', 'rb'))

In [89]:
probaYes = loadModel_tpot.predict_proba(dat1)[0][1]

In [90]:
dat1

0      1       2     3    4    5    6    7    8    9   10   11   12  \
0  56.0  4.857  93.994 -36.4  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0   

    13   14   15   16   17   18   19   20   21   22   23   24   25   26   27  
0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [91]:
result = 'The probability of accepting the bank offer is : {}'.format(probaYes)

In [92]:
result

'The probability of accepting the bank offer is : 0.013822262753849268'