In [2]:
# importing essential libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', None)

%matplotlib inline

In [3]:
bank = pd.read_csv('bank_ht.csv')

In [4]:
bank.head()

age  education  default  campaign  poutcome  cons.price.idx  cons.conf.idx  \
0   56          0        1         1         0          93.994          -36.4   
1   57          3        0         1         0          93.994          -36.4   
2   37          3        1         1         0          93.994          -36.4   
3   40          1        1         1         0          93.994          -36.4   
4   56          3        1         1         0          93.994          -36.4   

   euribor3m  job_blue-collar  job_entrepreneur  job_housemaid  \
0      4.857                0                 0              1   
1      4.857                0                 0              0   
2      4.857                0                 0              0   
3      4.857                0                 0              0   
4      4.857                0                 0              0   

   job_management  job_retired  job_self-employed  job_services  job_student  \
0               0            0                  0             0            0   
1               0            0                  0             1            0   
2               0            0                  0             1            0   
3               0            0                  0             0            0   
4               0            0                  0             1            0   

   job_technician  job_unemployed  job_unknown  marital_married  \
0               0               0            0                1   
1               0               0            0                1   
2               0               0            0                1   
3               0               0            0                1   
4               0               0            0                1   

   marital_single  housing_unknown  housing_yes  loan_yes  contact_telephone  \
0               0                0            0         0                  1   
1               0                0            0         0                  1   
2               0                0            1         0                  1   
3               0                0            0         0                  1   
4               0                0            0         1                  1   

   month_aug  month_dec  month_jul  month_jun  month_mar  month_may  \
0          0          0          0          0          0          1   
1          0          0          0          0          0          1   
2          0          0          0          0          0          1   
3          0          0          0          0          0          1   
4          0          0          0          0          0          1   

   month_nov  month_oct  month_sep  day_of_week_mon  day_of_week_thu  \
0          0          0          0                1                0   
1          0          0          0                1                0   
2          0          0          0                1                0   
3          0          0          0                1                0   
4          0          0          0                1                0   

   day_of_week_tue  day_of_week_wed   y  
0                0                0  no  
1                0                0  no  
2                0                0  no  
3                0                0  no  
4                0                0  no

In [5]:
bank.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41087 entries, 0 to 41086
Data columns (total 39 columns):
age                  41087 non-null int64
education            41087 non-null int64
default              41087 non-null int64
campaign             41087 non-null int64
poutcome             41087 non-null int64
cons.price.idx       41087 non-null float64
cons.conf.idx        41087 non-null float64
euribor3m            41087 non-null float64
job_blue-collar      41087 non-null int64
job_entrepreneur     41087 non-null int64
job_housemaid        41087 non-null int64
job_management       41087 non-null int64
job_retired          41087 non-null int64
job_self-employed    41087 non-null int64
job_services         41087 non-null int64
job_student          41087 non-null int64
job_technician       41087 non-null int64
job_unemployed       41087 non-null int64
job_unknown          41087 non-null int64
marital_married      41087 non-null int64
marital_single       41087 non-null int64
hou

In [6]:
features = bank.drop('y', axis = 1)
target = bank['y'].apply(lambda x: 1 if x == 'yes' else 0)

In [7]:
features.head()

age  education  default  campaign  poutcome  cons.price.idx  cons.conf.idx  \
0   56          0        1         1         0          93.994          -36.4   
1   57          3        0         1         0          93.994          -36.4   
2   37          3        1         1         0          93.994          -36.4   
3   40          1        1         1         0          93.994          -36.4   
4   56          3        1         1         0          93.994          -36.4   

   euribor3m  job_blue-collar  job_entrepreneur  job_housemaid  \
0      4.857                0                 0              1   
1      4.857                0                 0              0   
2      4.857                0                 0              0   
3      4.857                0                 0              0   
4      4.857                0                 0              0   

   job_management  job_retired  job_self-employed  job_services  job_student  \
0               0            0                  0             0            0   
1               0            0                  0             1            0   
2               0            0                  0             1            0   
3               0            0                  0             0            0   
4               0            0                  0             1            0   

   job_technician  job_unemployed  job_unknown  marital_married  \
0               0               0            0                1   
1               0               0            0                1   
2               0               0            0                1   
3               0               0            0                1   
4               0               0            0                1   

   marital_single  housing_unknown  housing_yes  loan_yes  contact_telephone  \
0               0                0            0         0                  1   
1               0                0            0         0                  1   
2               0                0            1         0                  1   
3               0                0            0         0                  1   
4               0                0            0         1                  1   

   month_aug  month_dec  month_jul  month_jun  month_mar  month_may  \
0          0          0          0          0          0          1   
1          0          0          0          0          0          1   
2          0          0          0          0          0          1   
3          0          0          0          0          0          1   
4          0          0          0          0          0          1   

   month_nov  month_oct  month_sep  day_of_week_mon  day_of_week_thu  \
0          0          0          0                1                0   
1          0          0          0                1                0   
2          0          0          0                1                0   
3          0          0          0                1                0   
4          0          0          0                1                0   

   day_of_week_tue  day_of_week_wed  
0                0                0  
1                0                0  
2                0                0  
3                0                0  
4                0                0

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
## Splitting the train and test sets

X_train, X_test, y_train, y_test = train_test_split(features, target,
                                                   test_size = 0.3, random_state = 101)

## Try dimension reduction

In [11]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [41]:
pca = PCA(n_components = 25)

In [42]:
scaler = StandardScaler()
Xtr_pca = scaler.fit_transform(X_train)

In [43]:
pca.fit(Xtr_pca)

PCA(copy=True, iterated_power='auto', n_components=25, random_state=None,
    svd_solver='auto', tol=0.0, whiten=False)

In [44]:
try1 = pca.transform(Xtr_pca)

In [45]:
try1.shape

(28760, 25)

In [46]:
X_train.shape

(28760, 38)

In [47]:
Xtr_pca.shape

(28760, 38)

In [48]:
sum(pca.explained_variance_ratio_)

0.8522475208225763

In [49]:
df = pd.DataFrame(scaler.fit_transform(features), columns = features.columns)

In [50]:
df_pca = pd.DataFrame(pca.fit_transform(df))

In [51]:
X_train_pca = df_pca.iloc[X_train.index]
X_test_pca = df_pca.iloc[X_test.index]
y_train_pca = target.iloc[X_train.index]
y_test_pca = target.iloc[X_test.index]

In [52]:
# initiating models

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score,roc_auc_score, f1_score, log_loss, matthews_corrcoef

In [53]:
log_reg = LogisticRegression(solver = 'saga', max_iter = 1000, class_weight = 'balanced')
rfc = RandomForestClassifier(class_weight = 'balanced', max_depth = 6)
xgb = XGBClassifier(scale_pos_weight = 7.75)

### Logistic Regression

In [54]:
## test logistic regression

log_reg.fit(X_train_pca, y_train_pca)

LogisticRegression(C=1.0, class_weight='balanced', dual=False,
                   fit_intercept=True, intercept_scaling=1, l1_ratio=None,
                   max_iter=1000, multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='saga', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
LogisticRegression()

In [55]:
pred_train = log_reg.predict(X_train_pca)

In [56]:
print(classification_report(y_train_pca,pred_train))

              precision    recall  f1-score   support

           0       0.95      0.80      0.87     25476
           1       0.29      0.65      0.40      3284

    accuracy                           0.78     28760
   macro avg       0.62      0.72      0.63     28760
weighted avg       0.87      0.78      0.81     28760



In [57]:
print(confusion_matrix(y_train_pca, pred_train))

[[20326  5150]
 [ 1163  2121]]


In [58]:
predictions = log_reg.predict(X_test_pca)

In [59]:
print(classification_report(y_test_pca,predictions))

              precision    recall  f1-score   support

           0       0.95      0.80      0.87     10987
           1       0.28      0.63      0.39      1340

    accuracy                           0.78     12327
   macro avg       0.61      0.71      0.63     12327
weighted avg       0.87      0.78      0.82     12327



In [60]:
print(confusion_matrix(y_test_pca, predictions))

[[8823 2164]
 [ 501  839]]


### Random Forest Classifier 

In [61]:
rfc.fit(X_train_pca, y_train_pca)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight='balanced',
                       criterion='gini', max_depth=6, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [62]:
rfc_train = rfc.predict(X_train_pca)

In [63]:
print(confusion_matrix(y_train_pca,rfc_train))

[[20957  4519]
 [ 1154  2130]]


In [64]:
print(classification_report(y_train_pca,rfc_train))

              precision    recall  f1-score   support

           0       0.95      0.82      0.88     25476
           1       0.32      0.65      0.43      3284

    accuracy                           0.80     28760
   macro avg       0.63      0.74      0.65     28760
weighted avg       0.88      0.80      0.83     28760



In [65]:
rfc_prediction = rfc.predict(X_test_pca)

In [66]:
print(confusion_matrix(y_test_pca,rfc_prediction))

[[9070 1917]
 [ 532  808]]


In [67]:
print(classification_report(y_test_pca,rfc_prediction))

              precision    recall  f1-score   support

           0       0.94      0.83      0.88     10987
           1       0.30      0.60      0.40      1340

    accuracy                           0.80     12327
   macro avg       0.62      0.71      0.64     12327
weighted avg       0.87      0.80      0.83     12327



### XGBClassifier

In [68]:
xgb.fit(X_train_pca, y_train_pca)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=7.75, subsample=1,
              tree_method=None, validate_parameters=False, verbosity=None)

In [69]:
xgb_train = xgb.predict(X_train_pca)

In [70]:
print(confusion_matrix(y_train_pca, xgb_train))

[[23316  2160]
 [  171  3113]]


In [71]:
print(classification_report(y_train_pca, xgb_train))

              precision    recall  f1-score   support

           0       0.99      0.92      0.95     25476
           1       0.59      0.95      0.73      3284

    accuracy                           0.92     28760
   macro avg       0.79      0.93      0.84     28760
weighted avg       0.95      0.92      0.93     28760



In [72]:
xgb_pred = xgb.predict(X_test_pca)

In [73]:
print(confusion_matrix(y_test_pca, xgb_pred))

[[9660 1327]
 [ 620  720]]


In [74]:
print(classification_report(y_test_pca, xgb_pred))

              precision    recall  f1-score   support

           0       0.94      0.88      0.91     10987
           1       0.35      0.54      0.43      1340

    accuracy                           0.84     12327
   macro avg       0.65      0.71      0.67     12327
weighted avg       0.88      0.84      0.86     12327



### Try finding a better pc

In [78]:
target_pca = target

In [79]:
## logistic regression

def try_w_pca1(df, train_index, test_index):
    scaler = StandardScaler()
    target = target_pca
    df = df.drop('y', axis = 1)
    df = pd.DataFrame(scaler.fit_transform(df), columns = df.columns)
    log_reg = LogisticRegression(solver = 'saga', max_iter = 1000, class_weight = 'balanced')
    for pc in range(10, 31, 5):
        pca = PCA(n_components = pc)
        df_pca =pd.DataFrame(pca.fit_transform(df))
        X_train_pca = df_pca.iloc[train_index]
        X_test_pca = df_pca.iloc[test_index]
        y_train_pca = target.iloc[train_index]
        y_test_pca = target.iloc[test_index]
        log_reg.fit(X_train_pca, y_train_pca)
        print('pc = {} and train'.format(pc))
        print(classification_report(y_train_pca, log_reg.predict(X_train_pca)))
        print('pc = {} and test'.format(pc))
        print(classification_report(y_test_pca, log_reg.predict(X_test_pca)))

In [80]:
try_w_pca1(bank, X_train.index, X_test.index)

pc = 10 and train
              precision    recall  f1-score   support

           0       0.95      0.75      0.84     25476
           1       0.26      0.67      0.37      3284

    accuracy                           0.74     28760
   macro avg       0.60      0.71      0.61     28760
weighted avg       0.87      0.74      0.78     28760

pc = 10 and test
              precision    recall  f1-score   support

           0       0.95      0.76      0.84     10987
           1       0.25      0.66      0.36      1340

    accuracy                           0.75     12327
   macro avg       0.60      0.71      0.60     12327
weighted avg       0.87      0.75      0.79     12327

pc = 15 and train
              precision    recall  f1-score   support

           0       0.95      0.79      0.86     25476
           1       0.29      0.65      0.40      3284

    accuracy                           0.77     28760
   macro avg       0.62      0.72      0.63     28760
weighted avg       0.

In [81]:
## for RFC

def try_w_pca2(df, train_index, test_index):
    scaler = StandardScaler()
    target = target_pca
    df = df.drop('y', axis = 1)
    df = pd.DataFrame(scaler.fit_transform(df), columns = df.columns)
    rfc = RandomForestClassifier(class_weight = 'balanced', max_depth = 6)
    for pc in range(10, 31, 5):
        pca = PCA(n_components = pc)
        df_pca =pd.DataFrame(pca.fit_transform(df))
        X_train_pca = df_pca.iloc[train_index]
        X_test_pca = df_pca.iloc[test_index]
        y_train_pca = target.iloc[train_index]
        y_test_pca = target.iloc[test_index]
        rfc.fit(X_train_pca, y_train_pca)
        print('pc = {} and train'.format(pc))
        print(classification_report(y_train_pca, rfc.predict(X_train_pca)))
        print('pc = {} and test'.format(pc))
        print(classification_report(y_test_pca, rfc.predict(X_test_pca)))

In [82]:
try_w_pca2(bank, X_train.index, X_test.index)

pc = 10 and train
              precision    recall  f1-score   support

           0       0.95      0.80      0.87     25476
           1       0.30      0.66      0.41      3284

    accuracy                           0.78     28760
   macro avg       0.62      0.73      0.64     28760
weighted avg       0.87      0.78      0.82     28760

pc = 10 and test
              precision    recall  f1-score   support

           0       0.95      0.80      0.87     10987
           1       0.28      0.62      0.39      1340

    accuracy                           0.78     12327
   macro avg       0.61      0.71      0.63     12327
weighted avg       0.87      0.78      0.82     12327

pc = 15 and train
              precision    recall  f1-score   support

           0       0.95      0.82      0.88     25476
           1       0.31      0.64      0.42      3284

    accuracy                           0.80     28760
   macro avg       0.63      0.73      0.65     28760
weighted avg       0.

In [83]:
## for XGB

def try_w_pca3(df, train_index, test_index):
    scaler = StandardScaler()
    target = target_pca
    df = df.drop('y', axis = 1)
    df = pd.DataFrame(scaler.fit_transform(df), columns = df.columns)
    xgb = XGBClassifier(scale_pos_weight = 7.75)
    for pc in range(10, 31, 5):
        pca = PCA(n_components = pc)
        df_pca =pd.DataFrame(pca.fit_transform(df))
        X_train_pca = df_pca.iloc[train_index]
        X_test_pca = df_pca.iloc[test_index]
        y_train_pca = target.iloc[train_index]
        y_test_pca = target.iloc[test_index]
        xgb.fit(X_train_pca, y_train_pca)
        print('pc = {} and train'.format(pc))
        print(classification_report(y_train_pca, xgb.predict(X_train_pca)))
        print('pc = {} and test'.format(pc))
        print(classification_report(y_test_pca, xgb.predict(X_test_pca)))

In [84]:
try_w_pca3(bank, X_train.index, X_test.index)

pc = 10 and train
              precision    recall  f1-score   support

           0       0.99      0.89      0.94     25476
           1       0.52      0.92      0.67      3284

    accuracy                           0.89     28760
   macro avg       0.75      0.91      0.80     28760
weighted avg       0.94      0.89      0.91     28760

pc = 10 and test
              precision    recall  f1-score   support

           0       0.94      0.86      0.90     10987
           1       0.31      0.54      0.40      1340

    accuracy                           0.82     12327
   macro avg       0.63      0.70      0.65     12327
weighted avg       0.87      0.82      0.84     12327

pc = 15 and train
              precision    recall  f1-score   support

           0       0.99      0.91      0.95     25476
           1       0.56      0.94      0.70      3284

    accuracy                           0.91     28760
   macro avg       0.78      0.92      0.82     28760
weighted avg       0.